---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  type: https
  interval: 1m0s
  url: https://charts.cloudposse.com/incubator/superset
