---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      interval: 1m
      url: https://charts.bitnami.com/bitnami
